# Salt.Box config is autogenerated for the container and should not be edit.

# Redis conf:
redis_host: 'redis-salt'
redis_username: '${REDIS_USERNAME}'
redis_password: '${REDIS_PASSWORD}'
redis_ssl_use: true
redis_ssl_ca_certs: '/etc/redis/certs/ca.crt'

# Time to live for job returns and grains (sec)
expire: 604800

gitfs_server: 'sshfs'
gitfs_port: 1022

sshfs_sync_on: false

# vi: ft=yaml
