target-version = "py37"
line-length = 120

[format]
quote-style = "single"
docstring-code-format = true

[lint]
preview = true
select = [
  "B",  # flake8-bugbear
  "C90",  # mccabe
  "C4",  # flake8-comprehensions
  "DTZ",  # flake8-datetimez https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  "EM",  # flake8-errmsg
  "UP",  # pyupgrade
  "FA",  # flake8-future-annotations
  "LOG",  # flake8-logging
  "PTH",  # flake8-use-pathlib
  "ASYNC",  # flake8-async
  "G",  # flake8-logging-format
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "S",  # flake8-bandit
  "W",  # pycodestyle warnings
  "N",  # pep8-naming
  "RUF",  # ruff checks
  "TD",  # flake8-todo
]
ignore = [
  "S404", "S603", # subprocess
  "S314", "S405", # XML parsing
]
fixable = ["ALL"]
unfixable = ["F401", "F841", "UP035"]

[lint.flake8-quotes]
docstring-quotes = "single"
inline-quotes = "single"
multiline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.mccabe]
max-complexity = 10

# vi: sw=2
