# For modules out of saltbox-bridge

target-version = 'py310'
line-length = 120

[lint]
preview = true
select = [
  'B',     # flake8-bugbear
  'C90',   # mccabe
  'C4',    # flake8-comprehensions
  'DTZ',   # flake8-datetimez https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  'EM',    # flake8-errmsg
  'UP',    # pyupgrade
  'FA',    # flake8-future-annotations
  'LOG',   # flake8-logging
  'PTH',   # flake8-use-pathlib
  'ASYNC', # flake8-async
  'G',     # flake8-logging-format
  'E',     # pycodestyle errors
  'F',     # pyflakes
  'I',     # isort
  'S',     # flake8-bandit
  'W',     # pycodestyle warnings
  'N',     # pep8-naming
  'RUF',   # ruff checks
  'TD',    # flake8-todo
]
ignore = [
  'E701',   # multiple statements on one line
  'E722',   # do not use bare except
  'ERA',    # do not autoremove commented out code
  'N818',   # error-suffix-on-exception-name
  'S314',   # using xml
  'S404',   # suspicious-subprocess-import
  'S405',    # import xml
  'S603',   # using subprocess
  'TD002',  # Missing author in TODO
  'TD003',  # Found TODO in code
  'UP040',  # type instead of TypeAlias PEP 695'
]
fixable = ['ALL']
unfixable = ['F401', 'F841', 'UP035']
