[supervisord]
user=root
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
environment=PYTHONUNBUFFERED=1

[program:salt-master]
command=/usr/local/bin/salt-master
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:salt-minion]
command=/bin/sh -c 'sleep 1 && exec /usr/local/bin/salt-minion'
priority=20
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# vi: syn=dosini
