from __future__ import annotations


class SaltBoxBridgeError(RuntimeError): ...


class CoreConnectionTimeoutError(SaltBoxBridgeError, TimeoutError): ...


class SaltCallerError(RuntimeError): ...


class SaltCallerTypeError(SaltCallerError, TypeError): ...


class CorePillarError(SaltBoxBridgeError): ...


class CorePillarTimeoutError(CorePillarError, TimeoutError): ...
